[package]
name = "snarkvm-algorithms-cuda"
version = "0.9.11"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Cuda optimizations for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"

[features]
default = [ ]
portable = [ "blst/portable" ]
quiet = [ ]

[dependencies.blst]
version = "0.3.9"
features = [ ]

[dependencies.sppark]
path="../../../zgf-sppark/rust"
#git = "https://github.com/supranational/sppark"
#rev = "48f6ac6"
#version = "0.1.3"

[build-dependencies.cc]
version = "^1.0.70"

[build-dependencies.which]
version = "^4.0"
